### ISSUE TITLE
WITH GRANT OPTION missing

### ISSUE THREAD

**Issue by riaanvddool** [orchardup/docker-mysql#1]
In https://github.com/orchardup/docker-mysql/blob/master/run#L17 :

```
GRANT ALL PRIVILEGES ON . TO 'root'@'%';
```

should read

```
GRANT ALL PRIVILEGES ON . TO 'root'@'%' WITH GRANT OPTION;
```

else the user 'root'@'%' is not able to grant privileges to other users.

See also https://github.com/sameersbn/docker-gitlab/issues/17

**Comment by bfirsh** [comment]
Thanks!
