### ISSUE TITLE
Run java fiile in LXC container

### ISSUE THREAD

**Issue by bhim3003** [orchardup/docker-mysql#12]
I created a docker image and installed java in that. How can i run a java file which is in my system through that  container.  Can a kinow about the commands and command line statements to compile and run a java file from anywhere by just using the docker image. How can i deploy an file to docker image?

**Comment by bfirsh** [comment]
Best to ask on the [docker-user mailing list](https://groups.google.com/forum/?fromgroups#!forum/docker-user) or the #docker IRC channel on Freenode.
